// Public surface. Consumers import from the package root.

export * from './domain';

// Babylon adapter exports (require @babylonjs/core peer dep)
export type {
  AtlasRect,
  EyeSpec,
  EngineHandles,
  PoolFactory,
  PoolFactoryResult,
  PooledItem,
  AcquireResult,
  PoolStats,
  ThinInstancePoolOptions,
  ThinInstanceHandle,
  ThinInstancePool,
  SharedShapeOpts,
  RenderLoopGateOpts,
  MasterTickOpts,
  DeviceProbeSignalSnapshot,
  DeviceProbeSignalSource,
  DeviceTierCap,
  DeviceCap,
  Rgb01,
  MeshRenderInterpolationHandle,
  RealismLodBudget,
} from './adapters/babylon';
export { AssetCache } from './adapters/babylon';
export {
  engineHandles,
  registerPoolType,
  getRegisteredPoolKeys,
  prewarmPool,
  hideAllPrewarmed,
  acquireFromPool,
  releaseTypeFromPool,
  releaseAllPools,
  getPoolStats,
  selectAllForPrewarmRender,
  beginPrewarmBatch,
  selectNewlyPrewarmedForRender,
  resetPrewarmSelect,
  createThinInstancePool,
  purgeShapeCache,
  sharedBoxAggregate,
  dimsKeyFor,
  startPoolTelemetry,
  stopPoolTelemetry,
  registerScenePurge,
  registeredPurgerCount,
  purgeAllSceneCaches,
  setupRenderLoopGate,
  suppressLogNoise,
  restoreLogNoise,
  installMasterTick,
  installPersistentShaderCache,
  uninstallPersistentShaderCache,
  setShadowGenerator,
  registerScriptedShadow,
  unregisterScriptedShadow,
  setPrimaryShadowCaster,
  getShadowReceivers,
  addShadowReceiver,
  removeShadowReceiver,
  setHighlightLayer,
  addHighlightedMesh,
  removeHighlightedMesh,
  clearHighlights,
  registerMotionBlurProcess,
  unregisterMotionBlurProcess,
  triggerMotionBlur,
  hexToRgb01,
  hexToColor3,
  hexToColor4,
  hexToCss,
  lightenHex,
  darkenHex,
  lightenRgb01,
  RenderPauser,
  applyBakedSunLight,
  applyBakedCavityAO,
  REALISM_LOD,
  realismSkin,
  mapPlanarUV,
  pinUvWhite,
  eyeRingColor,
  buildEyeSphere,
  fbmDisplace,
  paintVertexColor,
  paintCanary,
  organicTube,
  organicMembrane,
  attachMeshRenderInterpolation,
  readDrawCalls,
  readActiveIndices,
  readActiveTriangles,
  sumActiveVerts,
  applyEngineProfile,
  configureQualityPresetProvider,
  configurePBRLowMaskKeys,
  createUnlitEmissiveMat,
  createUnlitEmissiveCrystalMat,
  createSelfLitVertexColorMat,
  createLitVertexColorMat,
  createFlatLitVertexColorMat,
  createFlatLitMat,
  getDecorMatcap,
  createMatcapVertexColorMat,
  setDecorShadingMode,
  getDecorShadingMode,
  setCelFreezeMaterials,
  shouldFreezeUnderCel,
  MATCAP_EMISSIVE_FLOOR_K,
  MATCAP_G4_LEVEL,
  MATCAP_G4_CAVITY,
  DECOR_EMISSIVE_FLOOR,
  FLAT_EMISSIVE_FLOOR_K,
  acquireMaterial,
  acquirePBRMaterial,
  acquireTieredMaterial,
  releaseMaterial,
  releasePBRMaterial,
  disposeAllMaterials,
  peekMaterial,
  peekPBRMaterial,
  forceCompileMaterial,
  configureDeviceProbe,
  getDeviceCap,
  invalidateDeviceCap,
  getDeviceScaleCap,
  getDeviceTierCap,
  attachReprobeTriggers,
  persistLearnedCap,
  runDeviceProbe,
  setEngineErrorSink,
  setEnginePerformanceSink,
} from './adapters/babylon';
export type { DecorMatcapKind, DecorShadingMode } from './adapters/babylon';

// Web adapter exports
export {
  measureRefreshRate,
  startProbeDisplayRefresh,
  getProbedDisplayRefresh,
  getDisplayMaxHz,
  onDisplayMaxHz,
} from './adapters/web';

export type { GraphicEngine } from './ports/driving';
export type {
  Clock,
  KeyValueStorage,
  AudioProfileSink,
  DiagnosticsSink,
  ErrorContext,
  ErrorSink,
  PerfUnit,
  PerformanceSink,
  InputSource,
  NativeServices,
  RefreshMode,
  ThermalState,
  BatteryStatus,
  RefreshInfo,
  AsyncKeyValueStorage,
  RenderingBackend,
  PhysicsBackend,
} from './ports/driven';

export { createGraphicEngine } from './api';
export type { CreateGraphicEngineOptions, QualityPort, TierPort, PhasePort, FramePort, AssetsPort, MaterialsPort, PoolsPort, PhaseSink } from './api';

// Prototipo cel-shading (branch proto/cel-shading). Sperimentale: nessun
// consumatore di produzione, si toglie in blocco se il look non passa.
export * from './adapters/babylon/cel';
